name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag easydns-ddns-updater:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: user/app:latest, user/app:${{ github.run_number }}
